// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...3
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTRIXkLRnZU-347yFAl3jDqrBu5xmN-Y',
    appId: '1:933413662300:web:f6c0e5cee49d338fc44099',
    messagingSenderId: '933413662300',
    projectId: 'madcamp-week1-c108a',
    authDomain: 'madcamp-week1-c108a.firebaseapp.com',
    storageBucket: 'madcamp-week1-c108a.firebasestorage.app',
    measurementId: 'G-6VW4E1FSZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaseD3Tdusc3j9nlM7PGBVhHtcpT7itZE',
    appId: '1:933413662300:android:ba7b24b5065a1cc4c44099',
    messagingSenderId: '933413662300',
    projectId: 'madcamp-week1-c108a',
    storageBucket: 'madcamp-week1-c108a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2FyhFxbsZL5DGuNq8dCFY-iazHHxFkc',
    appId: '1:933413662300:ios:f820c29c4652df8cc44099',
    messagingSenderId: '933413662300',
    projectId: 'madcamp-week1-c108a',
    storageBucket: 'madcamp-week1-c108a.firebasestorage.app',
    iosBundleId: 'com.example.singasong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz2FyhFxbsZL5DGuNq8dCFY-iazHHxFkc',
    appId: '1:933413662300:ios:f820c29c4652df8cc44099',
    messagingSenderId: '933413662300',
    projectId: 'madcamp-week1-c108a',
    storageBucket: 'madcamp-week1-c108a.firebasestorage.app',
    iosBundleId: 'com.example.singasong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZTRIXkLRnZU-347yFAl3jDqrBu5xmN-Y',
    appId: '1:933413662300:web:8112e5fb5e796ab4c44099',
    messagingSenderId: '933413662300',
    projectId: 'madcamp-week1-c108a',
    authDomain: 'madcamp-week1-c108a.firebaseapp.com',
    storageBucket: 'madcamp-week1-c108a.firebasestorage.app',
    measurementId: 'G-J05YG97QR9',
  );
}
